site_name: ZJERS - 分享ZJE的一切
site_url: https://zjers.com
site_author: Zhouyue Zhu
site_description: "记录生活学习在ZJE，国际校区，乃至生活在海宁市的一些指南，用作参考。"
copyright: Copyright &copy; 2025 - Now ZJERS

repo_url: https://github.com/zhuzhouyue123/zjers
repo_name: zhuzhouyue123/zjers

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
    view: material/eye
  favicon: assets/logo.png
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.action.view


plugins:
  - search
  - glightbox
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zhuzhouyue123



edit_uri: edit/main/docs/


markdown_extensions:
  - abbr
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/app.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - 首页:
    - 首页: index.md
    - 贡献指南: contribute.md
  
  - 常用信息:
    - basics/index.md
    - Blackboard: basics/blackboard.md
    - PeopleSoft: basics/peoplesoft.md
    - MyZJU: basics/myzju.md

  - 课程:
    - 专业课:
      - 大一:
        - IBMS1(整合生物医学1): 
          - course/year1/IBMS1/index.md
        - IBI1(生物信息学导论): 
          - course/year1/IBI1/index.md
        - ICMB1(细胞分子生物学): 
          - course/year1/ICMB1/index.md
      - 大二:
        - IFBS2(生理学): 
          - course/year2/IFBS2/index.md
        - BG2(遗传):
          - course/year2/BG2/index.md
        - ADS2(应用数据科学):
          - course/year2/ADS2/index.md
        - DST2(数据库与软件技术):
          - course/year2/DST2/index.md
          - 浅谈Servlet: course/year2/DST2/servlet.md
        - GP2(基因组学与蛋白质组学):
          - course/year2/GP2/index.md
      - 大三:
        - IBMS3(整合生物医学3):
          - course/year3/IBMS3/index.md
        - MBE3(分子生物学与表观遗传学):
          - course/year3/MBE3/index.md
        - PoN3(神经科学):
          - course/year3/PoN3/index.md
      - 大四:
        - IID4:
          - course/year4/IID4/index.md
    - 通识课:
      - 体育: course/generalcourse/pe.md
  
  - 美食指南: 
    - foodmap/index.md
    - 早餐: 
      - foodmap/breakfast/index.md
      - 三棵柳千层饼: foodmap/breakfast/三棵柳千层饼.md
      - 煎饼姐姐饺子馆: foodmap/breakfast/煎饼姐姐饺子馆.md
      - 胡大菁馄饨: foodmap/breakfast/胡大菁馄饨.md
      - 袁记云饺: foodmap/breakfast/袁记云饺.md
      - 熊仔坊: foodmap/breakfast/熊仔坊.md
      - 麦当劳: foodmap/breakfast/麦当劳.md
      - 小江水: foodmap/breakfast/小江水.md
      - 多多馄饨: foodmap/breakfast/多多馄饨.md
    - 火锅/烤肉: 
      - foodmap/bbq-hotpot/index.md
    - 中国地方菜系: 
      - foodmap/chinese-cuisine/index.md
    - 外国料理: 
      - foodmap/foreign-cuisine/index.md
    - 小吃/快餐: 
      - foodmap/snack/index.md
    - 面包/蛋糕/甜品/饮品: 
      - foodmap/dessert/index.md
    - 其他: 
      - foodmap/others/index.md

  - 常用教程:
    - tutorial/index.md
    - 校区网络使用指南: tutorial/web.md
    - 浙大校外VPN使用教程: tutorial/vpn-zju.md
    - 爱大VPN使用教程: tutorial/vpn-ed.md
    - Zotero使用教程: tutorial/zotero.md
  
  - 友情链接:
    - links/index.md